code/src/main/java/br/ufes/inf/nemo/resgate/dispatch/controller/ManageIncidentController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.inf.nemo.resgate.dispatch.controller;

import br.ufes.inf.nemo.resgate.dispatch.application.ManageIncidentService;
import br.ufes.inf.nemo.resgate.dispatch.domain.Incident;
import br.ufes.inf.nemo.resgate.util.GoogleMapsUtil;
import br.ufes.inf.nemo.util.ejb3.application.CrudService;
import br.ufes.inf.nemo.util.ejb3.controller.CrudController;
import com.google.maps.model.LatLng;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author Thiago
 */
@Named
@SessionScoped
public class ManageIncidentController extends CrudController<Incident> {

    @EJB
    private ManageIncidentService manageIncidentService;

    public ManageIncidentController() {
        viewPath = "/manageIncident/";
        bundleName = "msgs";
    }

    @Override
    protected CrudService<Incident> getCrudService() {
        return manageIncidentService;
    }

    @Override
    protected Incident createNewEntity() {
        return new Incident();
    }

    @Override
    protected void initFilters() {

    }

}

code/src/main/java/br/ufes/inf/nemo/resgate/dispatch/controller/UtilController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.inf.nemo.resgate.dispatch.controller;

import br.ufes.inf.nemo.resgate.data.domain.EquipmentType;
import br.ufes.inf.nemo.resgate.data.domain.Hospital;
import br.ufes.inf.nemo.resgate.data.domain.StaffFunction;
import br.ufes.inf.nemo.resgate.data.persistence.HospitalDAO;
import br.ufes.inf.nemo.resgate.dispatch.domain.Incident;
import br.ufes.inf.nemo.resgate.dispatch.domain.IncidentState;
import br.ufes.inf.nemo.resgate.dispatch.domain.PriorityLevel;
import br.ufes.inf.nemo.resgate.dispatch.persistence.IncidentDAO;
import br.ufes.inf.nemo.util.ejb3.controller.PersistentObjectConverterFromId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.convert.Converter;
import javax.inject.Named;

/**
 *
 * @author Thiago
 */
@Named
@ApplicationScoped
public class UtilController {

    private List<StaffFunction> staffFunctions;

    private List<EquipmentType> equipmentTypes;

    private List<PriorityLevel> priorityLevels;

    private List<IncidentState> incidentStates;

    private List<Hospital> hospitals;

    @EJB
    private HospitalDAO hospitalDAO;

    @EJB
    private IncidentDAO incidentDAO;

    private PersistentObjectConverterFromId<Hospital> hospitalConverter;

    private PersistentObjectConverterFromId<Incident> incidentConverter;

    public List<StaffFunction> getStaffFunctions() {
        if (staffFunctions == null) {
            staffFunctions = new ArrayList<>();
            staffFunctions.addAll(Arrays.asList(StaffFunction.values()));
        }
        return staffFunctions;
    }

    public void setStaffFunctions(List<StaffFunction> staffFunctions) {
        this.staffFunctions = staffFunctions;
    }

    public List<EquipmentType> getEquipmentTypes() {
        if (equipmentTypes == null) {
            equipmentTypes = new ArrayList<>();
            equipmentTypes.addAll(Arrays.asList(EquipmentType.values()));
        }
        return equipmentTypes;
    }

    public void setEquipmentTypes(List<EquipmentType> equipmentTypes) {
        this.equipmentTypes = equipmentTypes;
    }

    public List<PriorityLevel> getPriorityLevels() {
        if (priorityLevels == null) {
            priorityLevels = new ArrayList<>();
            priorityLevels.addAll(Arrays.asList(PriorityLevel.values()));
        }
        return priorityLevels;
    }

    public void setPriorityLevels(List<PriorityLevel> priorityLevels) {
        this.priorityLevels = priorityLevels;
    }

    public Converter getHospitalController() {
        if (hospitalConverter == null) {
            hospitalConverter = new PersistentObjectConverterFromId<>(hospitalDAO);
        }
        return hospitalConverter;
    }

    public Converter getIndentConverter() {
        if (incidentConverter == null) {
            incidentConverter = new PersistentObjectConverterFromId<>(incidentDAO);
        }
        return incidentConverter;
    }

    public List<Hospital> getHospitals() {
        if (hospitals == null) {
            hospitals = hospitalDAO.retrieveAllActiveHospitals();
        }
        return hospitals;
    }

    public List<IncidentState> getIncidentStates() {
        if (incidentStates == null) {
            incidentStates = new ArrayList<>();
            incidentStates.addAll(Arrays.asList(IncidentState.values()));
        }
        return incidentStates;
    }

    public void setIncidentStates(List<IncidentState> incidentStates) {
        this.incidentStates = incidentStates;
    }

}

code/src/main/webapp/manageIncident/form.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/resources/templates/default/decorator.xhtml">

    <ui:define name="title">
        <h:outputText value="#{msgs['manageIncident.title.create']}" rendered="#{(! manageIncidentController.readOnly) and (manageIncidentController.selectedEntity.id == null)}" />
        <h:outputText value="#{msgs['manageIncident.title.update']}" rendered="#{(! manageIncidentController.readOnly) and (manageIncidentController.selectedEntity.id != null)}" />
        <h:outputText value="#{msgs['manageIncident.title.retrieve']}" rendered="#{manageIncidentController.readOnly}" />
    </ui:define>

    <ui:define name="body">
        <h1>
            <h:outputText value="#{msgs['manageIncident.title.create']}" rendered="#{(! manageIncidentController.readOnly) and (manageIncidentController.selectedEntity.id == null)}" />
            <h:outputText value="#{msgs['manageIncident.title.update']}" rendered="#{(! manageIncidentController.readOnly) and (manageIncidentController.selectedEntity.id != null)}" />
            <h:outputText value="#{msgs['manageIncident.title.retrieve']}" rendered="#{manageIncidentController.readOnly}" />
        </h1>

        <div class="crud">
            <ui:decorate template="/resources/templates/default/form.xhtml">
                <h:form id="form">
                    <p:hotkey bind="#{msgs['crud.hotkey.focusFirstField']}" handler="findObjectById('form:state').focus();" />

                    <h:panelGroup id="incidentStateField">
                        <ui:decorate template="/resources/templates/default/formfield.xhtml">
                            <ui:param name="fieldName" value="form:incidentState" />
                            <ui:param name="tooltip" value="#{msgs['manageIncident.form.state.tooltip']}" />
                            <ui:define name="label"><h:outputText value="#{msgs['manageIncident.form.state']}" /></ui:define>
                            <p:selectOneMenu 
                                id="incidentState" 
                                value="#{manageIncidentController.selectedEntity.incidentState}" 
                                required="true" 
                                disabled="#{manageIncidentController.readOnly}" 
                                converter="incidentStateConverter"
                                styleClass="selectOne"
                                requiredMessage="#{msgs['crud.required.field']}">
                                <f:selectItems
                                    value="#{utilController.incidentStates}" />
                                <p:ajax event="blur" update="incidentStateField" />
                            </p:selectOneMenu>
                        </ui:decorate>
                    </h:panelGroup>

                    <h:panelGroup id="priorityLevelField">
                        <ui:decorate template="/resources/templates/default/formfield.xhtml">
                            <ui:param name="fieldName" value="form:priorityLevel" />
                            <ui:param name="tooltip" value="#{msgs['manageIncident.form.priorityLevel.tooltip']}" />
                            <ui:define name="label"><h:outputText value="#{msgs['manageIncident.form.priorityLevel']}" /></ui:define>
                            <p:selectOneMenu 
                                id="priorityLevel" 
                                value="#{manageIncidentController.selectedEntity.priorityLevel}" 
                                required="true" 
                                styleClass="selectOne"
                                disabled="#{manageIncidentController.readOnly}" 
                                converter="priorityLevelConverter"
                                requiredMessage="#{msgs['crud.required.field']}">
                                <f:selectItems
                                    value="#{utilController.priorityLevels}" />
                                <p:ajax event="blur" update="priorityLevelField" />
                            </p:selectOneMenu>
                        </ui:decorate>
                    </h:panelGroup>

                    <ui:decorate template="/resources/templates/default/formfield.xhtml">
                        <ui:param name="hospital" value="form:hospital" />
                        <ui:param name="tooltip" value="#{msgs['manageIncident.form.hospital.tooltip']}" />
                        <ui:define name="label"><h:outputText value="#{msgs['manageIncident.form.hospital']}" /></ui:define>
                        <p:selectOneMenu 
                            id="hospital" 
                            value="#{manageIncidentController.selectedEntity.hospital}"
                            required="true" 
                            styleClass="selectOne"
                            disabled="#{manageIncidentController.readOnly}"
                            converter="#{utilController.hospitalController}"
                            requiredMessage="#{msgs['crud.required.field']}">
                            <f:selectItems
                                value="#{utilController.hospitals}" />
                        </p:selectOneMenu>
                    </ui:decorate>
                    <ui:decorate template="/resources/templates/default/formbutton.xhtml">
                        <h:panelGroup rendered="#{! manageIncidentController.readOnly}">
                            <p:commandButton 
                                action="#{manageIncidentController.list}" 
                                value="#{msgs['crud.button.cancel']}" 
                                immediate="true" 
                                icon="ui-icon-cancel1"
                                styleClass="btn-form btn" />
                            <p:commandButton 
                                action="#{manageIncidentController.save}" 
                                value="#{msgs['crud.button.save']}" 
                                update=":form :globalMessages" 
                                icon="ui-icon-save1"
                                styleClass="btn-form btn" />
                            <p:hotkey bind="#{msgs['crud.hotkey.backToList']}" action="#{manageIncidentController.list}" immediate="true" />
                            <p:hotkey bind="#{msgs['crud.hotkey.save']}" action="#{manageIncidentController.save}" update=":form :globalMessages" />
                        </h:panelGroup>
                        <h:panelGroup rendered="#{manageStationController.readOnly}">
                            <p:commandButton 
                                action="#{manageIncidentController.list}" 
                                value="#{msgs['crud.button.back']}" 
                                immediate="true" 
                                icon="ui-icon-save1"
                                styleClass="btn-form btn" />
                            <p:hotkey bind="#{msgs['crud.hotkey.backToList']}" action="#{manageIncidentController.list}" immediate="true" />
                        </h:panelGroup>
                    </ui:decorate>
                </h:form>
            </ui:decorate>
        </div>
    </ui:define>

    <ui:define name="help">
        <h4><h:outputText value="#{msgs['text.hotkeys']}" />:</h4>
        <ul>
            <li><b><h:outputText value="#{msgs['crud.hotkey.focusFirstField']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.focusFirstField']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.backToList']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.backToList']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.save']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.save']}" />.</li>
        </ul>
    </ui:define>
</ui:composition>

code/src/main/webapp/manageIncident/list.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/resources/templates/default/decorator.xhtml">

    <ui:define name="title"><h:outputText value="#{msgs['manageIncident.title']}" /></ui:define>

    <ui:define name="body">
        <h1><h:outputText value="#{msgs['manageIncident.title']}" /></h1>

        <div class="crud">
            <!-- Filter bar: used to filter the listing (displayed when there is at least one filter available). -->
            <h:form id="filterForm">
                <h:panelGroup id="filterBar" rendered="#{(not empty manageIncidentController.filters)}">
                    <div class="crudFilterBar">
                        <h:outputText value="#{msgs['crud.text.filter']} " />
                        <p:selectOneMenu id="filter" required="true" value="#{manageIncidentController.filterKey}">
                            <f:selectItems value="#{manageIncidentController.filters}" var="filter" itemLabel="#{filter.label}" itemValue="#{filter.key}" />
                            <f:ajax event="change" execute="@form" listener="#{manageIncidentController.changeFilter}" render="@form :listingForm :buttonsForm" />
                        </p:selectOneMenu>
                        <h:outputText value=": " />
                        <p:inputText id="filterText" size="20" required="false" value="#{manageIncidentController.filterParam}" rendered="#{manageIncidentController.filter.options == null}" />
                        <p:selectOneMenu id="filterSelect" required="false" value="#{manageIncidentController.filterParam}" rendered="#{manageIncidentController.filter.options != null}">
                            <f:selectItems value="#{manageIncidentController.filter.reversedOptionsLabels}" />
                        </p:selectOneMenu>
                        <p:commandLink action="#{manageIncidentController.filter}" process="@form" update=":listingForm :buttonsForm">
                            <h:graphicImage style="border: 0;" value="/resources/templates/default/icons/button-find.png" title="#{msgs['crud.button.filter']}" />
                        </p:commandLink>
                        <p:hotkey bind="#{msgs['crud.hotkey.filterFocus']}" handler="if (findObjectById('filterForm:filterText') != null) findObjectById('filterForm:filterText').focus(); else findObjectById('filterForm:filterSelect').focus();" />
                    </div>
                </h:panelGroup>
            </h:form>

            <!-- The listing form. -->
            <h:form id="listingForm">
                <!-- Filter information (displayed when the listing is being filtered. -->
                <h:panelGroup id="filterInfo" rendered="#{manageIncidentController.filtering}">
                    <div class="crudFilterInfo">
                        <h:outputFormat value="#{msgs['crud.text.filterInfo']} ">
                            <f:param value="#{manageIncidentController.filter.label}" />
                            <f:param value="#{manageIncidentController.filterLabel}" />
                        </h:outputFormat>
                        <p:commandLink action="#{manageIncidentController.cancelFilter}" process="@form" update="@form :buttonsForm">
                            <h:graphicImage style="border: 0;" value="/resources/templates/default/icons/button-close.png" title="#{msgs['crud.button.cancelFilter']}" />
                        </p:commandLink>
                        <p:hotkey bind="#{msgs['crud.hotkey.clearFilter']}" action="#{manageIncidentController.cancelFilter}" process="@form" update=":listingForm :buttonsForm" />
                    </div>
                </h:panelGroup>

                <!-- The list of entities. -->
                <h:panelGroup id="listing" styleClass="listing">
                    <p:dataTable
                        widgetVar="listingTable"
                        value="#{manageIncidentController.lazyEntities}" 
                        var="entity" 
                        rows="#{manageIncidentController.maxDataTableRowsPerPage}" 
                        rowsPerPageTemplate="#{manageIncidentController.halfMaxDataTableRowsPerPage},#{manageIncidentController.maxDataTableRowsPerPage},#{manageIncidentController.doubleMaxDataTableRowsPerPage}"
                        lazy="true" 
                        paginator="true" 
                        selection="#{manageIncidentController.selectedEntity}" 
                        selectionMode="single" 
                        paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}" 
                        paginatorPosition="bottom" 
                        emptyMessage="#{manageIncidentController.filtering ? msgs['manageIncident.text.noEntitiesFiltered'] : msgs['manageIncident.text.noEntities']}">

                        <p:column headerText="#{msgs['manageIncident.form.state']}">
                            <h:outputText value="#{entity.incidentState}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageIncident.form.priorityLevel']}">
                            <h:outputText value="#{entity.priorityLevel}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageIncident.form.ambulanceSettings']}">
                            <h:outputText value="#{entity.ambulanceSettings}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageIncident.form.dispatches']}">
                            <h:outputText value="#{entity.dispatches.size()}" />
                        </p:column>

                        <p:ajax event="rowSelect" update=":buttonsForm" />
                    </p:dataTable>
                    <p:hotkey bind="ctrl+left" handler="goToFirstPage(listingTable);" />
                    <p:hotkey bind="left" handler="goToPreviousPage(listingTable);" />
                    <p:hotkey bind="right" handler="goToNextPage(listingTable);" />
                    <p:hotkey bind="ctrl+right" handler="goToLastPage(listingTable);" />
                </h:panelGroup>
            </h:form>

            <!-- Buttons shown below the listing. -->
            <h:form id="buttonsForm">
                <div class="crudButtons">
                    <p:commandButton 
                        action="#{manageIncidentController.retrieve}" 
                        value="#{msgs['crud.button.retrieve']}" 
                        icon="buttonView" 
                        disabled="#{manageIncidentController.selectedEntity == null}" 
                        styleClass="btn-list btn"/>
                    <p:commandButton 
                        action="#{manageIncidentController.update}"
                        value="#{msgs['crud.button.update']}" 
                        icon="buttonEdit" 
                        disabled="#{manageIncidentController.selectedEntity == null}"
                        styleClass="btn-list btn"/>
                    <p:hotkey bind="#{msgs['crud.hotkey.retrieve']}" action="#{manageStationController.retrieve}" rendered="#{manageStationController.selectedEntity != null}" />
                    <p:hotkey bind="#{msgs['crud.hotkey.update']}" action="#{manageStationController.update}" rendered="#{manageStationController.selectedEntity != null}" />
                </div>
            </h:form>
        </div>

        <p>&nbsp;</p>

    </ui:define>

    <ui:define name="help">
        <h4><h:outputText value="#{msgs['text.hotkeys']}" />:</h4>
        <ul>
            <li><b><h:outputText value="#{msgs['crud.hotkey.filterFocus']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.filterFocus']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.clearFilter']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.clearFilter']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.create']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.create']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.retrieve']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.retrieve']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.update']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.update']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.delete']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.delete']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.cancelDeletion']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.cancelDeletion']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.confirmDeletion']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.confirmDeletion']}" />.</li>
        </ul>
    </ui:define>
</ui:composition>