code/src/main/java/br/ufes/inf/nemo/resgate/dispatch/controller/ManageDispatchController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.inf.nemo.resgate.dispatch.controller;

import br.ufes.inf.nemo.resgate.dispatch.application.ManageDispatchService;
import br.ufes.inf.nemo.resgate.dispatch.domain.Dispatch;
import br.ufes.inf.nemo.resgate.dispatch.domain.Incident;
import br.ufes.inf.nemo.resgate.util.Pair;
import br.ufes.inf.nemo.util.ejb3.application.CrudService;
import br.ufes.inf.nemo.util.ejb3.controller.CrudController;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author Thiago
 */
@Named
@SessionScoped
public class ManageDispatchController extends CrudController<Dispatch> {

    @EJB
    private ManageDispatchService manageDispatchService;

    private Incident incident;

    private List selectedAmbulancesToBeDispatched;

    public ManageDispatchController() {
        viewPath = "/manageDispatch/";
        bundleName = "msgs";

    }

    @Override
    protected CrudService<Dispatch> getCrudService() {
        return manageDispatchService;
    }

    @Override
    protected Dispatch createNewEntity() {
        return new Dispatch();
    }

    @Override
    protected void initFilters() {
    }

    public void setIncident(Incident incident) {
        this.incident = incident;
    }

    public Incident getIncident() {
        return incident;
    }

    public List<Incident> getIncidentsPendingDispatch() {
        return manageDispatchService.getIncidentsPendingDisptach();
    }

    public List<Pair> getAmbulanceDistanceToIncident() {
        return manageDispatchService.getAmbulancesByDistance(this.incident);
    }

    public void setSelectedAmbulancesToBeDispatched(List selectedAmbulancesToBeDispatched) {
        this.selectedAmbulancesToBeDispatched = selectedAmbulancesToBeDispatched;
    }

    public List getSelectedAmbulancesToBeDispatched() {
        return selectedAmbulancesToBeDispatched;
    }

    public String dispatch() {
        manageDispatchService.dispatchAmbulances(incident, selectedAmbulancesToBeDispatched);
        return "list.xhtml";
    }
}

code/src/main/webapp/manageDispatch/form.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/resources/templates/default/decorator.xhtml">

    <ui:define name="title">
        <h:outputText value="#{msgs['manageDispatch.title.create']}" rendered="#{(! manageDispatchController.readOnly) and (manageDispatchController.selectedEntity.id == null)}" />
        <h:outputText value="#{msgs['manageDispatch.title.update']}" rendered="#{(! manageDispatchController.readOnly) and (manageDispatchController.selectedEntity.id != null)}" />
        <h:outputText value="#{msgs['manageDispatch.title.retrieve']}" rendered="#{manageDispatchController.readOnly}" />
    </ui:define>

    <ui:define name="body">
        <h1>
            <h:outputText value="#{msgs['manageDispatch.title.create']}" rendered="#{(! manageDispatchController.readOnly) and (manageDispatchController.selectedEntity.id == null)}" />
            <h:outputText value="#{msgs['manageDispatch.title.update']}" rendered="#{(! manageDispatchController.readOnly) and (manageDispatchController.selectedEntity.id != null)}" />
            <h:outputText value="#{msgs['manageDispatch.title.retrieve']}" rendered="#{manageDispatchController.readOnly}" />
        </h1>

        <div class="crud">
            <ui:decorate template="/resources/templates/default/form.xhtml">
                <h:form id="form">
                    <p:hotkey bind="#{msgs['crud.hotkey.focusFirstField']}" handler="findObjectById('form:dateTime').focus();" />

                    <h:panelGroup id="listing" styleClass="listing">
                        <p:dataTable
                            widgetVar="listingTable"
                            value="#{manageDispatchController.ambulanceDistanceToIncident}" 
                            var="pair" 
                            rows="#{manageDispatchController.maxDataTableRowsPerPage}" 
                            rowsPerPageTemplate="#{manageDispatchController.halfMaxDataTableRowsPerPage},#{manageDispatchController.maxDataTableRowsPerPage},#{manageDispatchController.doubleMaxDataTableRowsPerPage}"
                            lazy="true" 
                            rowKey="#{pair.value1}"
                            paginator="true" 
                            selection="#{manageDispatchController.selectedAmbulancesToBeDispatched}" 
                            selectionMode="multiple" 
                            paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}" 
                            paginatorPosition="bottom" 
                            emptyMessage="#{manageDispatchController.filtering ? msgs['manageDispatch.text.noEntitiesFiltered'] : msgs['manageDispatch.text.noEntities']}">

                            <p:column headerText="#{msgs['manageDisptach.form.ambulancePlate']}">
                                <h:outputText value="#{pair.value1}" />
                            </p:column>
                            <p:column headerText="#{msgs['manageDisptach.form.distance']}">
                                <h:outputText value="#{pair.value2}" />
                            </p:column>
                        </p:dataTable>
                    </h:panelGroup>
                    <ui:decorate template="/resources/templates/default/formbutton.xhtml">
                        <p:commandButton 
                            action="#{manageDispatchController.dispatch}" 
                            value="#{msgs['manageDispatch.title.dispatch']}"
                            icon="ui-icon-save1"
                            update=":form :globalMessages"
                            styleClass="btn-form btn"
                            style="margin-top: 15px; "/>
                    </ui:decorate>
                </h:form>
            </ui:decorate>
        </div>
    </ui:define>
</ui:composition>

code/src/main/webapp/manageDispatch/list.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/resources/templates/default/decorator.xhtml">

    <ui:define name="title"><h:outputText value="#{msgs['manageDispatch.title']}" /></ui:define>

    <ui:define name="body">
        <h1><h:outputText value="#{msgs['manageDispatch.title']}" /></h1>

        <div class="crud">
            <!-- Filter bar: used to filter the listing (displayed when there is at least one filter available). -->
            <h:form id="filterForm">
                <h:panelGroup id="filterBar" rendered="#{(not empty manageDispatchController.filters)}">
                    <div class="crudFilterBar">
                        <h:outputText value="#{msgs['crud.text.filter']} " />
                        <p:selectOneMenu id="filter" required="true" value="#{manageDispatchController.filterKey}">
                            <f:selectItems value="#{manageDispatchController.filters}" var="filter" itemLabel="#{filter.label}" itemValue="#{filter.key}" />
                            <f:ajax event="change" execute="@form" listener="#{manageDispatchController.changeFilter}" render="@form :listingForm :buttonsForm" />
                        </p:selectOneMenu>
                        <h:outputText value=": " />
                        <p:inputText id="filterText" size="20" required="false" value="#{manageDispatchController.filterParam}" rendered="#{manageDispatchController.filter.options == null}" />
                        <p:selectOneMenu id="filterSelect" required="false" value="#{manageDispatchController.filterParam}" rendered="#{manageDispatchController.filter.options != null}">
                            <f:selectItems value="#{manageDispatchController.filter.reversedOptionsLabels}" />
                        </p:selectOneMenu>
                        <p:commandLink action="#{manageDispatchController.filter}" process="@form" update=":listingForm :buttonsForm">
                            <h:graphicImage style="border: 0;" value="/resources/templates/default/icons/button-find.png" title="#{msgs['crud.button.filter']}" />
                        </p:commandLink>
                        <p:hotkey bind="#{msgs['crud.hotkey.filterFocus']}" handler="if (findObjectById('filterForm:filterText') != null) findObjectById('filterForm:filterText').focus(); else findObjectById('filterForm:filterSelect').focus();" />
                    </div>
                </h:panelGroup>
            </h:form>

            <!-- The listing form. -->
            <h:form id="listingForm">
                <!-- Filter information (displayed when the listing is being filtered. -->
                <h:panelGroup id="filterInfo" rendered="#{manageDispatchController.filtering}">
                    <div class="crudFilterInfo">
                        <h:outputFormat value="#{msgs['crud.text.filterInfo']} ">
                            <f:param value="#{manageDispatchController.filter.label}" />
                            <f:param value="#{manageDispatchController.filterLabel}" />
                        </h:outputFormat>
                        <p:commandLink action="#{manageDispatchController.cancelFilter}" process="@form" update="@form :buttonsForm">
                            <h:graphicImage style="border: 0;" value="/resources/templates/default/icons/button-close.png" title="#{msgs['crud.button.cancelFilter']}" />
                        </p:commandLink>
                        <p:hotkey bind="#{msgs['crud.hotkey.clearFilter']}" action="#{manageDispatchController.cancelFilter}" process="@form" update=":listingForm :buttonsForm" />
                    </div>
                </h:panelGroup>

                <!-- The list of entities. -->
                <h:panelGroup id="listing" styleClass="listing">
                    <p:dataTable
                        widgetVar="listingTable"
                        value="#{manageDispatchController.incidentsPendingDispatch}" 
                        var="entity" 
                        rows="#{manageDispatchController.maxDataTableRowsPerPage}" 
                        rowsPerPageTemplate="#{manageDispatchController.halfMaxDataTableRowsPerPage},#{manageDispatchController.maxDataTableRowsPerPage},#{manageDispatchController.doubleMaxDataTableRowsPerPage}"
                        lazy="true" 
                        rowKey="#{entity.id}"
                        paginator="true" 
                        selection="#{manageDispatchController.incident}" 
                        selectionMode="single" 
                        paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}" 
                        paginatorPosition="bottom" 

                        emptyMessage="#{manageDispatchController.filtering ? msgs['manageDispatch.text.noEntitiesFiltered'] : msgs['manageDispatch.text.noEntities']}">

                        <p:column headerText="#{msgs['manageDisptach.form.incidentPriorityLevel']}">
                            <h:outputText value="#{entity.priorityLevel}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageAddress.form.street']}">
                            <h:outputText value="#{entity.address.street}" />
                        </p:column>

                        <p:column headerText="#{msgs['manageAddress.form.zipCode']}">
                            <h:outputText value="#{entity.address.zipCode}" />
                        </p:column>

                        <p:column headerText="#{msgs['manageAddress.form.neighborhood']}">
                            <h:outputText value="#{entity.address.neighborhood}" />
                        </p:column>

                        <p:column headerText="#{msgs['manageAddress.form.city']}">
                            <h:outputText value="#{entity.address.city}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageDisptach.form.numberAmbulances']}">
                            <h:outputText value="#{entity.ambulanceSettings.size()}" />
                        </p:column>
                    </p:dataTable>
                    <p:hotkey bind="ctrl+left" handler="goToFirstPage(listingTable);" />
                    <p:hotkey bind="left" handler="goToPreviousPage(listingTable);" />
                    <p:hotkey bind="right" handler="goToNextPage(listingTable);" />
                    <p:hotkey bind="ctrl+right" handler="goToLastPage(listingTable);" />
                </h:panelGroup>
                <div class="crudButtons">
                    <p:commandButton 
                        action="#{manageDispatchController.create}" 
                        value="#{msgs['manageDispatch.title.dispatch']}" 
                        icon="buttonView" 
                        styleClass="btn-list btn"
                        style="margin-top: 15px"/>
                    <p:hotkey bind="#{msgs['crud.hotkey.create']}" action="#{manageDispatchController.create}" rendered="#{manageDispatchController.incident != null}" />
                </div>
            </h:form>
        </div>

        <p>&nbsp;</p>

    </ui:define>
</ui:composition>