code/src/main/java/br/ufes/inf/nemo/resgate/data/controller/DataController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.inf.nemo.resgate.data.controller;

import br.ufes.inf.nemo.resgate.data.domain.Station;
import br.ufes.inf.nemo.resgate.data.persistence.StationDAO;
import br.ufes.inf.nemo.util.ejb3.controller.PersistentObjectConverterFromId;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.convert.Converter;
import javax.inject.Named;

/**
 *
 * @author Thiago
 */
@Named
@ApplicationScoped
public class DataController implements Serializable {

    @EJB
    private StationDAO stationDAO;

    public List<Station> getActiveStations() {
        return stationDAO.retrieveAllActiveStations();
    }

    public Converter getStationConverter() {
        return new PersistentObjectConverterFromId<>(stationDAO);
    }
}

code/src/main/java/br/ufes/inf/nemo/resgate/data/controller/ManageAmbulanceController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.inf.nemo.resgate.data.controller;

import br.ufes.inf.nemo.resgate.data.application.ManageAmbulanceService;
import br.ufes.inf.nemo.resgate.data.domain.Ambulance;
import br.ufes.inf.nemo.util.ejb3.application.CrudService;
import br.ufes.inf.nemo.util.ejb3.controller.CrudController;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author thiago
 */
@Named
@SessionScoped
public class ManageAmbulanceController extends CrudController<Ambulance> {

    @EJB
    private ManageAmbulanceService manageAmbulanceService;

    public ManageAmbulanceController() {
        viewPath = "/manageAmbulance/";
        bundleName = "msgs";
    }

    @Override
    protected CrudService<Ambulance> getCrudService() {
        return manageAmbulanceService;
    }

    @Override
    protected Ambulance createNewEntity() {
        return new Ambulance();
    }

    @Override
    protected void initFilters() {
    }

}

code/src/main/webapp/manageAmbulance/form.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:b="http://bootsfaces.net/ui"
                template="/resources/templates/default/decorator.xhtml">

    <ui:define name="title">
        <h:outputText value="#{msgs['manageAmbulance.title.create']}" rendered="#{(! manageAmbulanceController.readOnly) and (manageAmbulanceController.selectedEntity.id == null)}" />
        <h:outputText value="#{msgs['manageAmbulance.title.update']}" rendered="#{(! manageAmbulanceController.readOnly) and (manageAmbulanceController.selectedEntity.id != null)}" />
        <h:outputText value="#{msgs['manageAmbulance.title.retrieve']}" rendered="#{manageAmbulanceController.readOnly}" />
    </ui:define>

    <ui:define name="body">
        <h1>
            <h:outputText value="#{msgs['manageAmbulance.title.create']}" rendered="#{(! manageAmbulanceController.readOnly) and (manageAmbulanceController.selectedEntity.id == null)}" />
            <h:outputText value="#{msgs['manageAmbulance.title.update']}" rendered="#{(! manageAmbulanceController.readOnly) and (manageAmbulanceController.selectedEntity.id != null)}" />
            <h:outputText value="#{msgs['manageAmbulance.title.retrieve']}" rendered="#{manageAmbulanceController.readOnly}" />
        </h1>

        <div class="crud">
            <ui:decorate template="/resources/templates/default/form.xhtml">
                <h:form id="form">
                    <p:hotkey bind="#{msgs['crud.hotkey.focusFirstField']}" handler="findObjectById('form:plate').focus();" />

                    <h:panelGroup id="plateField">
                        <ui:decorate template="/resources/templates/default/formfield.xhtml">
                            <ui:param name="fieldName" value="form:plate" />
                            <ui:param name="tooltip" value="#{msgs['manageAmbulance.form.plate.tooltip']}" />
                            <ui:define name="label"><h:outputText value="#{msgs['manageAmbulance.form.plate']}" /></ui:define>
                            <b:inputText id="plate" 
                                         value="#{manageAmbulanceController.selectedEntity.plate}" 
                                         size="50" 
                                         required="true" 
                                         disabled="#{manageAmbulanceController.readOnly}"
                                         requiredMessage="#{msgs['crud.required.field']}">
                                <f:facet name="prepend">
                                    <b:iconAwesome name="barcode" />
                                </f:facet>
                            </b:inputText>
                        </ui:decorate>
                    </h:panelGroup>

                    <h:panelGroup id="stationField">
                        <ui:decorate template="/resources/templates/default/formfield.xhtml">
                            <ui:param name="fieldName" value="form:station" />
                            <ui:param name="tooltip" value="#{msgs['manageAmbulance.form.station.tooltip']}" />
                            <ui:define name="label"><h:outputText value="#{msgs['manageAmbulance.form.station']}" /></ui:define>
                            <p:selectOneMenu 
                                id="station" 
                                value="#{manageAmbulanceController.selectedEntity.station}" 
                                required="true" 
                                styleClass="selectOne"
                                disabled="#{manageAmbulanceController.readOnly}" 
                                converter="#{dataController.stationConverter}"
                                requiredMessage="#{msgs['crud.required.field']}">
                                <f:selectItems
                                    value="#{dataController.activeStations}" />
                                <p:ajax event="blur" update="stationField" />
                            </p:selectOneMenu>
                        </ui:decorate>
                    </h:panelGroup>

                    <ui:decorate template="/resources/templates/default/formbutton.xhtml">
                        <h:panelGroup rendered="#{! manageAmbulanceController.readOnly}">
                            <p:commandButton 
                                action="#{manageAmbulanceController.list}" 
                                value="#{msgs['crud.button.cancel']}" 
                                immediate="true" 
                                icon="ui-icon-cancel1"
                                styleClass="btn-form btn"/>
                            <p:commandButton 
                                action="#{manageAmbulanceController.save}" 
                                value="#{msgs['crud.button.save']}" 
                                icon="ui-icon-save1"
                                update=":form :globalMessages" 
                                styleClass="btn-form btn"/>
                            <p:hotkey bind="#{msgs['crud.hotkey.backToList']}" action="#{manageAmbulanceController.list}" immediate="true" />
                            <p:hotkey bind="#{msgs['crud.hotkey.save']}" action="#{manageAmbulanceController.save}" update=":form :globalMessages" />
                        </h:panelGroup>
                        <h:panelGroup rendered="#{manageAmbulanceController.readOnly}">
                            <p:commandButton 
                                action="#{manageAmbulanceController.list}" 
                                value="#{msgs['crud.button.back']}" 
                                immediate="true" 
                                icon="ui-icon-save1"
                                styleClass="btn-form btn" />
                            <p:hotkey bind="#{msgs['crud.hotkey.backToList']}" action="#{manageAmbulanceController.list}" immediate="true" />
                        </h:panelGroup>
                    </ui:decorate>
                </h:form>
            </ui:decorate>
        </div>
    </ui:define>

    <ui:define name="help">
        <h4><h:outputText value="#{msgs['text.hotkeys']}" />:</h4>
        <ul>
            <li><b><h:outputText value="#{msgs['crud.hotkey.focusFirstField']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.focusFirstField']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.backToList']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.backToList']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.save']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.save']}" />.</li>
        </ul>
    </ui:define>
</ui:composition>

code/src/main/webapp/manageAmbulance/list.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/resources/templates/default/decorator.xhtml">

    <ui:define name="title"><h:outputText value="#{msgs['manageAmbulance.title']}" /></ui:define>

    <ui:define name="body">
        <h1><h:outputText value="#{msgs['manageAmbulance.title']}" /></h1>

        <div class="crud">
            <!-- Filter bar: used to filter the listing (displayed when there is at least one filter available). -->
            <h:form id="filterForm">
                <h:panelGroup id="filterBar" rendered="#{(not empty manageAmbulanceController.filters)}">
                    <div class="crudFilterBar">
                        <h:outputText value="#{msgs['crud.text.filter']} " />
                        <p:selectOneMenu id="filter" required="true" value="#{manageAmbulanceController.filterKey}">
                            <f:selectItems value="#{manageAmbulanceController.filters}" var="filter" itemLabel="#{filter.label}" itemValue="#{filter.key}" />
                            <f:ajax event="change" execute="@form" listener="#{manageAmbulanceController.changeFilter}" render="@form :listingForm :buttonsForm" />
                        </p:selectOneMenu>
                        <h:outputText value=": " />
                        <p:inputText id="filterText" size="20" required="false" value="#{manageAmbulanceController.filterParam}" rendered="#{manageAmbulanceController.filter.options == null}" />
                        <p:selectOneMenu id="filterSelect" required="false" value="#{manageAmbulanceController.filterParam}" rendered="#{manageAmbulanceController.filter.options != null}">
                            <f:selectItems value="#{manageAmbulanceController.filter.reversedOptionsLabels}" />
                        </p:selectOneMenu>
                        <p:commandLink action="#{manageAmbulanceController.filter}" process="@form" update=":listingForm :buttonsForm">
                            <h:graphicImage style="border: 0;" value="/resources/templates/default/icons/button-find.png" title="#{msgs['crud.button.filter']}" />
                        </p:commandLink>
                        <p:hotkey bind="#{msgs['crud.hotkey.filterFocus']}" handler="if (findObjectById('filterForm:filterText') != null) findObjectById('filterForm:filterText').focus(); else findObjectById('filterForm:filterSelect').focus();" />
                    </div>
                </h:panelGroup>
            </h:form>

            <!-- The listing form. -->
            <h:form id="listingForm">
                <!-- Filter information (displayed when the listing is being filtered. -->
                <h:panelGroup id="filterInfo" rendered="#{manageAmbulanceController.filtering}">
                    <div class="crudFilterInfo">
                        <h:outputFormat value="#{msgs['crud.text.filterInfo']} ">
                            <f:param value="#{manageAmbulanceController.filter.label}" />
                            <f:param value="#{manageAmbulanceController.filterLabel}" />
                        </h:outputFormat>
                        <p:commandLink action="#{manageAmbulanceController.cancelFilter}" process="@form" update="@form :buttonsForm">
                            <h:graphicImage style="border: 0;" value="/resources/templates/default/icons/button-close.png" title="#{msgs['crud.button.cancelFilter']}" />
                        </p:commandLink>
                        <p:hotkey bind="#{msgs['crud.hotkey.clearFilter']}" action="#{manageAmbulanceController.cancelFilter}" process="@form" update=":listingForm :buttonsForm" />
                    </div>
                </h:panelGroup>

                <!-- The list of entities. -->
                <h:panelGroup id="listing" styleClass="listing">
                    <p:dataTable
                        widgetVar="listingTable"
                        value="#{manageAmbulanceController.lazyEntities}" 
                        var="entity" 
                        rows="#{manageAmbulanceController.maxDataTableRowsPerPage}" 
                        rowsPerPageTemplate="#{manageAmbulanceController.halfMaxDataTableRowsPerPage},#{manageAmbulanceController.maxDataTableRowsPerPage},#{manageAmbulanceController.doubleMaxDataTableRowsPerPage}"
                        lazy="true" 
                        paginator="true" 
                        selection="#{manageAmbulanceController.selectedEntity}" 
                        selectionMode="single" 
                        paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}" 
                        paginatorPosition="bottom" 
                        emptyMessage="#{manageAmbulanceController.filtering ? msgs['manageAmbulance.text.noEntitiesFiltered'] : msgs['manageAmbulance.text.noEntities']}">

                        <p:column headerText="#{msgs['manageAmbulance.form.plate']}">
                            <h:outputText value="#{entity.plate}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageAmbulance.form.ambulanceState']}">
                            <h:outputText value="#{entity.ambulanceState}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageAmbulance.form.station']}">
                            <h:outputText value="#{entity.station}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageAmbulance.form.latitude']}">
                            <h:outputText value="#{entity.latitude}" />
                        </p:column>
                        <p:column headerText="#{msgs['manageAmbulance.form.longitude']}">
                            <h:outputText value="#{entity.longitude}" />
                        </p:column>

                        <p:ajax event="rowSelect" update=":buttonsForm" />
                    </p:dataTable>
                    <p:hotkey bind="ctrl+left" handler="goToFirstPage(listingTable);" />
                    <p:hotkey bind="left" handler="goToPreviousPage(listingTable);" />
                    <p:hotkey bind="right" handler="goToNextPage(listingTable);" />
                    <p:hotkey bind="ctrl+right" handler="goToLastPage(listingTable);" />
                </h:panelGroup>
            </h:form>

            <!-- Buttons shown below the listing. -->
            <h:form id="buttonsForm">
                <div class="crudButtons">
                    <p:commandButton 
                        action="#{manageAmbulanceController.create}" 
                        value="#{msgs['crud.button.create']}"
                        icon="buttonNew"
                        styleClass="btn-list btn"/>
                    <p:commandButton 
                        action="#{manageAmbulanceController.retrieve}" 
                        value="#{msgs['crud.button.retrieve']}" 
                        icon="buttonView" 
                        disabled="#{manageAmbulanceController.selectedEntity == null}" 
                        styleClass="btn-list btn"/>
                    <p:commandButton 
                        action="#{manageAmbulanceController.update}"
                        value="#{msgs['crud.button.update']}" 
                        icon="buttonEdit" 
                        disabled="#{manageAmbulanceController.selectedEntity == null}"
                        styleClass="btn-list btn"/>
                    <p:commandButton 
                        action="#{manageAmbulanceController.trash}" 
                        value="#{msgs['crud.button.delete']}" 
                        icon="buttonTrash"
                        disabled="#{manageAmbulanceController.selectedEntity == null}" 
                        process="@this" 
                        update=":trashForm"
                        styleClass="btn-list btn"/>
                    <p:hotkey bind="#{msgs['crud.hotkey.create']}" action="#{manageAmbulanceController.create}" />
                    <p:hotkey bind="#{msgs['crud.hotkey.retrieve']}" action="#{manageAmbulanceController.retrieve}" rendered="#{manageAmbulanceController.selectedEntity != null}" />
                    <p:hotkey bind="#{msgs['crud.hotkey.update']}" action="#{manageAmbulanceController.update}" rendered="#{manageAmbulanceController.selectedEntity != null}" />
                    <p:hotkey bind="#{msgs['crud.hotkey.delete']}" action="#{manageAmbulanceController.trash}" rendered="#{manageAmbulanceController.selectedEntity != null}" process="@this" update=":trashForm" />
                </div>
            </h:form>

            <!-- The trash panel: shows entities that have been selected for deletion. -->
            <h:form id="trashForm">
                <p:panel id="trashPanel" styleClass="trashPanel" header="#{msgs['crud.text.trashHeader']}" toggleable="true" rendered="#{not empty manageAmbulanceController.trashCan}">
                    <p:dataList value="#{manageAmbulanceController.trashCan}" var="entity" type="unordered">
                        #{entity.plate}
                    </p:dataList>
                    <div class="nemoUtilsFormInternalButton">
                        <p:commandButton action="#{manageAmbulanceController.cancelDeletion}" value="#{msgs['crud.button.cancelDeletion']}" icon="buttonCancel" update=":trashForm :buttonsForm :listingForm" />
                        <p:commandButton action="#{manageAmbulanceController.delete}" value="#{msgs['crud.button.confirmDeletion']}" icon="buttonOk" />
                        <p:hotkey bind="#{msgs['crud.hotkey.cancelDeletion']}" action="#{manageAmbulanceController.cancelDeletion}" update=":trashForm :buttonsForm :listingForm" />
                        <p:hotkey bind="#{msgs['crud.hotkey.confirmDeletion']}" action="#{manageAmbulanceController.delete}" />
                    </div>
                </p:panel>
            </h:form>
        </div>

        <p>&nbsp;</p>

    </ui:define>

    <ui:define name="help">
        <h4><h:outputText value="#{msgs['text.hotkeys']}" />:</h4>
        <ul>
            <li><b><h:outputText value="#{msgs['crud.hotkey.filterFocus']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.filterFocus']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.clearFilter']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.clearFilter']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.create']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.create']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.retrieve']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.retrieve']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.update']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.update']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.delete']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.delete']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.cancelDeletion']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.cancelDeletion']}" />;</li>
            <li><b><h:outputText value="#{msgs['crud.hotkey.confirmDeletion']}" /></b>: <h:outputText value="#{msgs['crud.help.hotkeys.confirmDeletion']}" />.</li>
        </ul>
    </ui:define>
</ui:composition>