code/src/main/java/br/ufes/inf/nemo/resgate/data/controller/ManageSessionController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.inf.nemo.resgate.data.controller;

import br.ufes.inf.nemo.resgate.data.application.ManageSessionService;
import br.ufes.inf.nemo.resgate.data.domain.Employee;
import br.ufes.inf.nemo.resgate.data.domain.StaffFunction;
import br.ufes.inf.nemo.util.ejb3.controller.JSFController;
import java.util.Date;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Thiago
 */
@Named
@SessionScoped
public class ManageSessionController extends JSFController {

    private static final long serialVersionUID = 1L;

    @EJB
    private ManageSessionService manageSessionService;

    private String username;

    private String password;

    private Employee currentUser;

    public ManageSessionController() {
        bundleName = "msgs";
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isLoggedIn() {
        return currentUser != null;
    }

    public boolean beforeLogin() {
        currentUser = null;
        return true;
    }

    public Employee getCurrentUser() {
        return currentUser;
    }

    public Date getNow() {
        return new Date(System.currentTimeMillis());
    }

    public Date getSessionExpirationTime() {
        Date expTime = null;

        // Attempts to retrieve this information from the external context.
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if (session != null) {
            long expTimeMillis = session.getLastAccessedTime() + session.getMaxInactiveInterval() * 1000;
            expTime = new Date(expTimeMillis);
        }

        // If it could not be retrieved from the external context, use default of 30 minutes.
        if (expTime == null) {
            expTime = new Date(System.currentTimeMillis() + 30 * 60000);
        }

        return expTime;
    }

    public String login() {
        try {
            currentUser = manageSessionService.login(username, password);
        } catch (Exception e) {
            addGlobalI18nMessage("msgs", FacesMessage.SEVERITY_ERROR, "error.login.summary", "error.login.detail");
            return null;
        }
        return "/manageDispatch/list.xhtml";
    }

    public String logout() {
        username = "";
        password = "";
        currentUser = null;
        return "/index.faces";
    }

    public boolean isAdmin() {
        return currentUser.getStaffFunctions().contains(StaffFunction.ADMIN);
    }

    public boolean isAttendant() {
        return currentUser.getStaffFunctions().contains(StaffFunction.ATTENDANT);
    }

    public String getWelcome() {
        return getI18nMessage("msgs", "menu.welcome") + " " + currentUser.getName();
    }
}

code/src/main/webapp/resources/templates/default/decorator.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Resgate</title>
        <meta name="author" content="Riccardo Massera"></meta>
    </h:head>
    <h:body style="padding-top: 60px">
        <!--<h:outputScript library="holder" name="holder.js" />-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.5.2/holder.min.js"></script>
        <link href='https://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css' />
        <h:outputStylesheet name="templates/default/stylesheets/style.css" />
        <b:navBar brand="Resgate" brandHref="#" inverse="true" fixed="top" fluid="true">


            <b:navbarLinks pull="right" rendered="#{manageSessionController.loggedIn}">
                <b:navLink value="#{manageSessionController.welcome}" href="#"></b:navLink>
                <b:navLink value="#{msgs['menu.logout']}" href="/index.faces"  />
            </b:navbarLinks>

        </b:navBar>
        <b:container fluid="true">
            <b:row>
                <b:column col-sm="3" col-md="2" styleClass="sidebar">
                    <b:listLinks rendered="#{manageSessionController.loggedIn and (manageSessionController.admin or manageSessionController.attendant)}" >
                        <b:navLink href="/manageEmergencyCall/list.faces" value="#{msgs['menu.manage.emergencyCall']}"/>
                        <b:navLink href="/manageIncident/list.faces" value="#{msgs['menu.manage.incident']}" />
                        <b:navLink href="/manageDispatch/list.faces" value="#{msgs['menu.manage.dispatch']}" />
                        <b:navLink href="/MDTSimulator/mdt.faces" value="#{msgs['mdt.simulator']}" />
                    </b:listLinks>
                    <b:listLinks rendered="#{manageSessionController.loggedIn and manageSessionController.admin}" >
                        <b:navLink href="/manageEmployee/list.faces" value="#{msgs['menu.manage.employee']}"/>
                        <b:navLink href="/manageAmbulance/list.faces" value="#{msgs['menu.manage.ambulance']}" />
                        <b:navLink href="/manageHospital/list.faces" value="#{msgs['menu.manage.hospital']}" />
                        <b:navLink href="/manageEquipment/list.faces" value="#{msgs['menu.manage.equipment']}" />
                        <b:navLink href="/manageStation/list.faces" value="#{msgs['menu.manage.station']}" />
                    </b:listLinks>
                </b:column>
                <b:column col-sm="9" offset-sm="3" col-md="10" offset="2" styleClass="main">
                    <h:form id="globalMessages">
                        <p:growl id="messages" globalOnly="true" showSummary="true" showDetail="true" sticky="true" />
                    </h:form>

                    <!-- Page contents: -->
                    <ui:insert name="body" />
                </b:column>
            </b:row>
        </b:container>                
    </h:body>
</html>

code/src/main/webapp/resources/templates/default/form.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">

    <div class="nemoUtilsForm">
        <f:validateBean>
            <ui:insert />
        </f:validateBean>
    </div>
</ui:composition>

code/src/main/webapp/resources/templates/default/formbutton.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">

    <div class="nemoUtilsFormButton">
        <ui:insert />
    </div>
</ui:composition>

code/src/main/webapp/resources/templates/default/formfield-novalidation.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <div class="nemoUtilsFormField">
        <div class="label">
            <ui:insert name="label" />:
        </div>
        <div class="field">
            <p:message for="#{fieldName}" rendered="#{fieldName != null}" />
            <ui:insert />
        </div>
        <div class="clear"></div>
    </div>
</ui:composition>

code/src/main/webapp/resources/templates/default/formfield-single.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <div class="nemoUtilsFormField nemoUtilsFormFieldSingle">
        <div class="label">
            <ui:insert name="label" /><h:panelGroup styleClass="star" rendered="#{(fieldName != null and facesContext.viewRoot.findComponent(fieldName).required)}">*</h:panelGroup>:
        </div>
        <div class="field">
            <p:message for="#{fieldName}" rendered="#{fieldName != null}" />
            <ui:insert />
            <p:tooltip for="#{fieldName}" value="#{tooltip}" rendered="#{tooltip != null}" showEvent="focus" hideEvent="blur" />
        </div>
        <div class="clear"></div>
    </div>
</ui:composition>

code/src/main/webapp/resources/templates/default/formfield.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <div class="nemoUtilsFormField #{(fieldName == null or empty facesContext.getMessageList(fieldName)) ? '' : 'nemoUtilsFormFieldError'}">
        <div class="label">
            <ui:insert name="label" /><h:panelGroup styleClass="star" rendered="#{(fieldName != null and facesContext.viewRoot.findComponent(fieldName).required)}">*</h:panelGroup>:
        </div>
        <div class="field">
            <p:message for="#{fieldName}" rendered="#{fieldName != null}" />
            <ui:insert />
            <p:tooltip for="#{fieldName}" value="#{tooltip}" rendered="#{tooltip != null}" showEvent="focus" hideEvent="blur" />
        </div>
        <div class="clear"></div>
    </div>
</ui:composition>